package log.in;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.FileInputStream;
import javax.swing.ImageIcon;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ra$h
 */
public class registration extends javax.swing.JFrame {

    /**
     * Creates new form registration
     */
   //Image path 
    String imagePath = null;
    
    ///
    String ImageName = null;
    byte[] image = null;
    
    public registration() {
        initComponents();
        
        
        //create gender group
        ButtonGroup ButtonGroup = new ButtonGroup();
        ButtonGroup.add(jRadioButton1_Male);
        ButtonGroup.add(jRadioButton2_Female);
                
                

        
        
    }

    
    public ImageIcon ResizeImage(String imagePath, byte [] pic){
    
    ImageIcon myImage = null;
    
    if (imagePath != null){
    
    myImage = new ImageIcon(imagePath);
    
    }else {
       myImage = new ImageIcon(pic);
    }
    
    Image img = myImage.getImage();
    Image img2 = img.getScaledInstance(jLabel8_ImageViewer.getWidth(), jLabel8_ImageViewer.getHeight(), Image.SCALE_SMOOTH);
    
    ImageIcon image = new ImageIcon(img2);
    return image;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1_ReUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2_ReLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2_ViewImage = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRadioButton1_Male = new javax.swing.JRadioButton();
        jRadioButton2_Female = new javax.swing.JRadioButton();
        jTextField5_ReFirstName = new javax.swing.JTextField();
        jLabel5_imagePath = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4_PhoneNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8_ImageViewer = new javax.swing.JLabel();
        Image_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Password");

        jLabel4.setText("Confirm Password");

        jButton2_ViewImage.setText("view Image");
        jButton2_ViewImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_ViewImageActionPerformed(evt);
            }
        });

        jButton3.setText("Add User");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jRadioButton1_Male.setSelected(true);
        jRadioButton1_Male.setText("Male");

        jRadioButton2_Female.setText("Female");
        jRadioButton2_Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2_FemaleActionPerformed(evt);
            }
        });

        jLabel5_imagePath.setText("path");

        jLabel6.setText("Phone number");

        jTextField4_PhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4_PhoneNumberKeyTyped(evt);
            }
        });

        jLabel7.setText("First Name");

        jPasswordField1.setText("jPasswordField1");

        jPasswordField2.setText("jPasswordField2");

        jLabel5.setText("Gender");

        Image_button.setText("Test");
        Image_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Image_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8_ImageViewer, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton1_Male)
                                        .addGap(28, 28, 28)
                                        .addComponent(jRadioButton2_Female))
                                    .addComponent(jTextField2_ReLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(jTextField1_ReUsername)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Image_button)
                                .addGap(160, 160, 160)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5_ReFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jButton2_ViewImage, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel5_imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_ReUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5_ReFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2_ReLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5_imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton1_Male)
                        .addComponent(jRadioButton2_Female)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2_ViewImage, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Image_button)
                        .addGap(99, 99, 99)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8_ImageViewer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4_PhoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4_PhoneNumberKeyTyped
        // TODO add your handling code here:
        
        if(!Character.isDigit(evt.getKeyChar()))
        {
        evt.consume();
        }
            
    }//GEN-LAST:event_jTextField4_PhoneNumberKeyTyped

    private void jButton2_ViewImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_ViewImageActionPerformed
        // TODO add your handling code here:
        
        String image_Path;
        JFileChooser imageSelecter = new JFileChooser();
        
        imageSelecter.setCurrentDirectory(new File(System.getProperty("user.home") ));
        
        //file extension
        FileNameExtensionFilter imageExtension = new FileNameExtensionFilter("*.Images","jpg","png","jpeg");
        
        imageSelecter.addChoosableFileFilter(imageExtension);
        
        Integer fileState = imageSelecter.showSaveDialog(null);
        
        //check if the user select
        if(fileState == JFileChooser.APPROVE_OPTION){
            
            File selectedImage = imageSelecter.getSelectedFile();
            image_Path = selectedImage.getAbsolutePath();
            
            jLabel8_ImageViewer.setIcon(ResizeImage(imagePath, null));
            
           // jLabel5_imagePath.setText(image_Path);
            //imagePath = image_Path;
            /////
           //ImageIcon myImage = imagePath;
            
           /////////////
        }
        
        
        
        
    }//GEN-LAST:event_jButton2_ViewImageActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String userName = jTextField1_ReUsername.getText();
        String firstName = jTextField5_ReFirstName.getText();
        String lastName  = jTextField2_ReLastName.getText();
        String password = String.valueOf(jPasswordField1.getPassword());
        String conPassword = String.valueOf(jPasswordField2.getPassword());
        String phone = jTextField4_PhoneNumber.getText();      
        String gender = "male";
        
        if ( jRadioButton2_Female.isSelected()){
           gender = "Female";
        }
        
        if( varifyFields())
        {
           if(!checkUser(userName))
           {
               PreparedStatement PreparedStatement;
               ResultSet ResultSet;
               
               String userQuery = "INSERT INTO `users`(`username`, `firstName`,"
                       + " `lastName`, `password`, `gender`, `phone`, `image`)"
                       + " VALUES (?,?,?,?,?,?,?)";
               
               try {
                   
                   //PreparedStatement = sql_connector.getConnection().preparedStatement(userQuery);
                    PreparedStatement = sql_connector.getSqlConnection().prepareStatement(userQuery);
                    PreparedStatement.setString(1, userName);
                    PreparedStatement.setString(2, firstName);
                    PreparedStatement.setString(3, lastName);
                    PreparedStatement.setString(4, password);
                    PreparedStatement.setString(5, gender);
                    PreparedStatement.setString(6, phone);
                    PreparedStatement.setNull(7, java.sql.Types.NULL);
                    
                    try {
                        
                        if(imagePath != null){
                         //save image
                         InputStream image = new FileInputStream(new File(imagePath));
                         PreparedStatement.setBlob(7,image);
                        }
                         
                    if (PreparedStatement.executeUpdate() != 0){
                    JOptionPane.showMessageDialog(null, "User Added");
                    
                    }  else{
                        JOptionPane.showMessageDialog(null, "Error check information");
                    }
                    
                         

                   } catch (Exception ex){
                            Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
                       
                   }
                    

                  
               } catch (Exception ex) {
               
                  Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
                 
               }
           
           }
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton2_FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2_FemaleActionPerformed

    private void Image_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Image_buttonActionPerformed
        // TODO add your handling code here: test button
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
       File f = chooser.getSelectedFile();
       ImageName = f.getAbsolutePath();
      // ImageIcon imageIcon = new ImageIcon (new ImageIcon(ImageName).getImage().getScaledInstance(jLabel8_ImageViewer.getWidth(), jLabel8_ImageViewer.getHeight(),Image.SCALE_SMOOTH));
        //jLabel8_ImageViewer.setIcon(imageIcon);
       // Image scaledImage = image.getScaledInstance(jLabel8_ImageViewer.getWidth(),jLabel8_ImageViewer.getHeight(),Image.SCALE_SMOOTH);
       ImageIcon imageIcon = new ImageIcon (new ImageIcon(ImageName).getImage().getScaledInstance(jLabel8_ImageViewer.getWidth(), jLabel8_ImageViewer.getHeight(),Image.SCALE_SMOOTH));

        
        jLabel8_ImageViewer.setIcon(new ImageIcon(f.toString()));

        ImageName=f.getAbsolutePath();
        //jLabel8_ImageViewer.setText(ImageName);
        
        
    }//GEN-LAST:event_Image_buttonActionPerformed

    
    public boolean varifyFields ()
    {
        
    String userName = jTextField1_ReUsername.getText();
    String firstName = jTextField5_ReFirstName.getText();
    String lastName  = jTextField2_ReLastName.getText();
    String password = String.valueOf(jPasswordField1.getPassword());
    String conPassword = String.valueOf(jPasswordField2.getPassword());
    String phone = jTextField4_PhoneNumber.getText();
    
       if (userName.trim().equals("") || firstName.trim().equals("") || lastName.trim().equals("")
              || password.trim().equals("") || conPassword.trim().equals("") || phone.trim().equals("") )
       {
       
           JOptionPane.showMessageDialog(null, " 1" ,"empty field",2 );
           return false;
       
       }
       
       else if(!password.equals(conPassword)){
               JOptionPane.showMessageDialog(null,"password doesn`t match","enter a matching password",2);
               return false;
               }
           else{
            return true;
        }
    
    }
     
    public boolean checkUser(String userName){
    
        PreparedStatement PreparedStatement;
        ResultSet ResultSet;
        boolean userExist = false;
        
        String query = "SELECT * FROM `users` WHERE `username` = ?";
        
        
           try {
            
            PreparedStatement = sql_connector.getSqlConnection().prepareStatement(query);
            PreparedStatement.setString(1, userName);
            ResultSet = PreparedStatement.executeQuery();
        
            if(ResultSet.next())
            {
                userExist = true;
                JOptionPane.showMessageDialog(null, "This Username is Already Taken, Choose Another One", "Username Failed", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return userExist;
        
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new registration().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Image_button;
    private javax.swing.JButton jButton2_ViewImage;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5_imagePath;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8_ImageViewer;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1_Male;
    private javax.swing.JRadioButton jRadioButton2_Female;
    private javax.swing.JTextField jTextField1_ReUsername;
    private javax.swing.JTextField jTextField2_ReLastName;
    private javax.swing.JTextField jTextField4_PhoneNumber;
    private javax.swing.JTextField jTextField5_ReFirstName;
    // End of variables declaration//GEN-END:variables
}
